<?php

namespace Database\Seeders;

use App\Models\Broadcast;
use App\Models\User;
use Illuminate\Database\Seeder;

class BroadcastSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::query()->where('email', UserSeeder::SUPER_ADMIN_EMAIL)->value('id');
        $images = ['/images/broadcasts/broadcast-01.svg', '/images/broadcasts/broadcast-02.svg', '/images/broadcasts/broadcast-03.svg', '/images/broadcasts/broadcast-04.svg', '/images/broadcasts/broadcast-05.svg', '/images/broadcasts/broadcast-06.svg'];

        foreach ($this->rows() as $index => $row) {
            Broadcast::query()->updateOrCreate(
                ['slug' => $row['slug']],
                array_merge($row, [
                    'featured_image' => $images[$index % count($images)],
                    'created_by' => $adminId,
                ]),
            );
        }
    }

    /**
     * Ordered newest first. Six rows per type keep the "related" block full.
     *
     * @return array<int, array<string, mixed>>
     */
    private function rows(): array
    {
        return [
            [
                'slug' => 'opengovportal-0-7-0-kini-tersedia',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-09-08 09:00:00',
                'title_ms' => 'OpenGovPortal 0.7.0 kini tersedia',
                'title_en' => 'OpenGovPortal 0.7.0 is now available',
                'excerpt_ms' => 'Versi 0.7.0 membawa tindakan AI dalam editor kandungan, penjanaan ringkasan automatik dan pembaikan pada menu pengepala.',
                'excerpt_en' => 'Version 0.7.0 brings AI actions in the content editor, automatic excerpt generation and fixes to the header menu.',
                'content_ms' => '<p>Pasukan OpenGovPortal hari ini mengeluarkan versi 0.7.0. Keluaran ini memberi tumpuan kepada pasukan kandungan: editor teks kaya kini mempunyai tindakan untuk memperbaiki tatabahasa, meringkaskan dan menterjemah teks ke bahasa kedua tanpa meninggalkan borang.</p><p>Turut disertakan ialah penjanaan ringkasan automatik untuk siaran dan pencapaian, tetapan kaki laman yang lebih mudah diurus serta pembaikan pada navigasi submenu di pengepala.</p><p>Pentadbir boleh melihat senarai perubahan penuh pada halaman Versi Platform di panel pentadbiran. Kemas kini tidak memerlukan perubahan pada pangkalan data.</p>',
                'content_en' => '<p>The OpenGovPortal team released version 0.7.0 today. This release is aimed at content teams: the rich text editor now has actions to fix grammar, summarise and translate text into the second language without leaving the form.</p><p>Also included are automatic excerpt generation for broadcasts and achievements, easier footer settings management and fixes to submenu navigation in the header.</p><p>Administrators can read the full change list on the Platform Version page in the admin panel. The update does not require any database changes.</p>',
            ],
            [
                'slug' => 'penyelenggaraan-berjadual-20-september-2026',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-09-01 10:00:00',
                'title_ms' => 'Penyelenggaraan berjadual pada 20 September 2026',
                'title_en' => 'Scheduled maintenance on 20 September 2026',
                'excerpt_ms' => 'Portal tidak dapat diakses selama kira-kira 30 minit bermula 2:00 pagi untuk naik taraf pangkalan data.',
                'excerpt_en' => 'The portal will be unavailable for about 30 minutes from 2:00 am for a database upgrade.',
                'content_ms' => '<p>Portal ini akan menjalani penyelenggaraan berjadual pada hari Ahad, 20 September 2026, dari 2:00 pagi hingga 2:30 pagi. Sepanjang tempoh tersebut, halaman awam dan panel pentadbiran tidak dapat diakses.</p><p>Kerja yang dijalankan termasuk naik taraf versi PostgreSQL dan pengindeksan semula kandungan carian. Tiada tindakan diperlukan daripada pengguna.</p><p>Jika penyelenggaraan mengambil masa lebih lama daripada dijangka, kemas kini akan disiarkan di halaman ini.</p>',
                'content_en' => '<p>This portal will undergo scheduled maintenance on Sunday, 20 September 2026, from 2:00 am to 2:30 am. During that window the public pages and the admin panel will be unavailable.</p><p>The work includes a PostgreSQL version upgrade and a full rebuild of the search index. No action is required from users.</p><p>If the maintenance takes longer than expected, updates will be posted on this page.</p>',
            ],
            [
                'slug' => 'pembantu-ai-kini-dalam-fasa-beta',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-08-25 09:30:00',
                'title_ms' => 'Pembantu AI kini dalam fasa beta',
                'title_en' => 'AI assistant now in beta',
                'excerpt_ms' => 'Widget sembang baharu menjawab soalan berdasarkan kandungan portal ini sahaja, dalam dua bahasa.',
                'excerpt_en' => 'A new chat widget answers questions from the content of this portal only, in both languages.',
                'content_ms' => '<p>Pembantu AI kini tersedia di setiap halaman awam sebagai widget sembang di penjuru kanan bawah. Ia menjawab soalan dalam Bahasa Malaysia atau Bahasa Inggeris menggunakan kandungan yang telah diterbitkan di portal ini sahaja.</p><p>Beberapa perkara yang perlu diketahui semasa fasa beta:</p><ul><li>Jawapan disertakan pautan sumber supaya anda boleh menyemak halaman asal.</li><li>Setiap pelawat dihadkan kepada sepuluh mesej sejam.</li><li>Perbualan tidak dikaitkan dengan identiti anda. Jangan kongsi maklumat peribadi.</li></ul><p>Maklum balas mengenai kualiti jawapan boleh dihantar melalui halaman Hubungi Kami.</p>',
                'content_en' => '<p>The AI assistant is now available on every public page as a chat widget in the bottom-right corner. It answers questions in Bahasa Malaysia or English using only content that has been published on this portal.</p><p>A few things to know during the beta:</p><ul><li>Answers include source links so you can check the original page.</li><li>Each visitor is limited to ten messages per hour.</li><li>Conversations are not linked to your identity. Do not share personal information.</li></ul><p>Feedback on answer quality can be sent through the Contact Us page.</p>',
            ],
            [
                'slug' => 'audit-kebolehcapaian-wcag-2-1-aa-selesai',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-08-11 09:00:00',
                'title_ms' => 'Audit kebolehcapaian WCAG 2.1 AA selesai',
                'title_en' => 'WCAG 2.1 AA accessibility audit completed',
                'excerpt_ms' => 'Kesemua sepuluh halaman awam lulus audit bebas tanpa isu kritikal.',
                'excerpt_en' => 'All ten public pages passed an independent audit with no critical issues.',
                'content_ms' => '<p>Audit kebolehcapaian bebas terhadap OpenGovPortal telah selesai pada Ogos 2026. Kesemua sepuluh halaman awam dinilai terhadap kriteria WCAG 2.1 tahap AA menggunakan pembaca skrin, navigasi papan kekunci dan alat semakan kontras.</p><p>Tiada isu kritikal ditemui. Tiga isu kecil yang dilaporkan, iaitu susunan fokus pada menu mudah alih, label pada butang carian dan kontras teks pada lencana jenis siaran, telah dibetulkan dalam versi 0.7.0.</p><p>Laporan penuh disimpan bersama dokumentasi projek dan audit akan diulang pada setiap keluaran utama.</p>',
                'content_en' => '<p>An independent accessibility audit of OpenGovPortal was completed in August 2026. All ten public pages were assessed against WCAG 2.1 level AA using screen readers, keyboard-only navigation and contrast checking tools.</p><p>No critical issues were found. Three minor issues that were reported, namely focus order in the mobile menu, the label on the search button and text contrast on broadcast type badges, were fixed in version 0.7.0.</p><p>The full report is kept with the project documentation and the audit will be repeated at every major release.</p>',
            ],
            [
                'slug' => 'cara-menerbitkan-siaran-pertama-anda',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-08-04 11:00:00',
                'title_ms' => 'Cara menerbitkan siaran pertama anda',
                'title_en' => 'How to publish your first broadcast',
                'excerpt_ms' => 'Panduan ringkas lima langkah dari log masuk hingga siaran muncul di laman utama.',
                'excerpt_en' => 'A short five-step guide from logging in to seeing your broadcast on the homepage.',
                'content_ms' => '<p>Panduan ini ditujukan kepada editor kandungan yang baru diberi akses ke panel pentadbiran.</p><ol><li>Log masuk dan pilih <strong>Siaran</strong> di bawah kumpulan Kandungan.</li><li>Klik <strong>Cipta</strong> dan isi tajuk dalam Bahasa Malaysia. Tajuk Bahasa Inggeris boleh diisi kemudian atau dijana dengan tindakan Terjemah.</li><li>Pilih jenis siaran: Siaran Media, Pengumuman atau Berita. Jenis ini menentukan lencana pada kad dan penapis di halaman senarai.</li><li>Tambah ringkasan tidak lebih daripada dua ayat. Ringkasan inilah yang dipaparkan pada kad laman utama.</li><li>Tetapkan status kepada Diterbitkan dan simpan. Siaran akan muncul di laman utama dalam masa satu minit selepas cache dikemas kini.</li></ol><p>Untuk menjadualkan penerbitan, isi tarikh dan masa pada medan Diterbitkan Pada. Siaran dengan tarikh hadapan tidak akan dipaparkan sehingga masa tersebut.</p>',
                'content_en' => '<p>This guide is for content editors who have just been given access to the admin panel.</p><ol><li>Log in and choose <strong>Broadcasts</strong> under the Content group.</li><li>Click <strong>Create</strong> and enter the title in Bahasa Malaysia. The English title can be filled in later or generated with the Translate action.</li><li>Pick the broadcast type: Press Release, Announcement or News. The type sets the badge on the card and the filter on the listing page.</li><li>Add an excerpt of no more than two sentences. This is what appears on the homepage card.</li><li>Set the status to Published and save. The broadcast appears on the homepage within a minute once the cache refreshes.</li></ol><p>To schedule publishing, set a date and time in the Published At field. A broadcast with a future date stays hidden until that time.</p>',
            ],
            [
                'slug' => 'sesi-latihan-untuk-editor-kandungan',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-07-28 09:00:00',
                'title_ms' => 'Sesi latihan untuk editor kandungan',
                'title_en' => 'Training sessions for content editors',
                'excerpt_ms' => 'Dua sesi dalam talian pada Ogos merangkumi editor, terjemahan dan penjadualan penerbitan.',
                'excerpt_en' => 'Two online sessions in August covering the editor, translation and scheduled publishing.',
                'content_ms' => '<p>Pasukan Sokongan &amp; Latihan akan mengadakan dua sesi latihan dalam talian untuk editor kandungan pada bulan Ogos. Setiap sesi berlangsung selama 90 minit dan dijalankan dalam Bahasa Malaysia dengan bahan rujukan dalam kedua-dua bahasa.</p><ul><li><strong>Sesi 1, 12 Ogos 2026, 10:00 pagi:</strong> asas panel pentadbiran, editor teks kaya dan pengurusan media.</li><li><strong>Sesi 2, 19 Ogos 2026, 10:00 pagi:</strong> tindakan AI, terjemahan, penjadualan penerbitan dan sejarah versi.</li></ul><p>Pendaftaran dibuka kepada semua pengguna berdaftar. Hantar nama dan sesi pilihan anda melalui halaman Hubungi Kami. Rakaman akan dikongsi dengan peserta selepas setiap sesi.</p>',
                'content_en' => '<p>The Support &amp; Training team will run two online training sessions for content editors in August. Each session lasts 90 minutes and is delivered in Bahasa Malaysia with reference material in both languages.</p><ul><li><strong>Session 1, 12 August 2026, 10:00 am:</strong> admin panel basics, the rich text editor and media management.</li><li><strong>Session 2, 19 August 2026, 10:00 am:</strong> AI actions, translation, scheduled publishing and version history.</li></ul><p>Registration is open to all registered users. Send your name and preferred session through the Contact Us page. Recordings will be shared with participants after each session.</p>',
            ],
            [
                'slug' => 'editor-kandungan-berbantu-ai-dilancarkan',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-07-14 09:00:00',
                'title_ms' => 'Editor kandungan berbantu AI dilancarkan',
                'title_en' => 'AI-assisted content editor launched',
                'excerpt_ms' => 'Editor kini boleh membaiki tatabahasa, meringkaskan dan menterjemah teks dengan pembekal AI pilihan pentadbir.',
                'excerpt_en' => 'Editors can now fix grammar, summarise and translate text with the AI provider chosen by the administrator.',
                'content_ms' => '<p>OpenGovPortal kini menyediakan tindakan berbantu AI terus di dalam editor teks kaya. Editor boleh memilih teks dan menjalankan tindakan Baiki Tatabahasa, Ringkaskan, Kembangkan atau Terjemah tanpa menyalin kandungan ke alat luaran.</p><p>Pentadbir memilih pembekal dan model AI melalui halaman Tetapan AI. Kunci API disimpan secara tersulit dan setiap panggilan direkodkan tanpa menyimpan kandungan teks, selaras dengan Dasar Penggunaan AI dalam Kandungan.</p><p>Ciri ini dimatikan secara lalai dan boleh diaktifkan oleh pentadbir utama apabila pembekal telah dikonfigurasi.</p>',
                'content_en' => '<p>OpenGovPortal now offers AI-assisted actions directly inside the rich text editor. Editors can select text and run Fix Grammar, Summarise, Expand or Translate without copying content to an external tool.</p><p>Administrators choose the AI provider and model on the AI Settings page. API keys are stored encrypted and every call is logged without storing the text itself, in line with the AI Use in Content Policy.</p><p>The feature is off by default and can be switched on by a super admin once a provider has been configured.</p>',
            ],
            [
                'slug' => 'di-sebalik-tabir-carian-dwibahasa',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-06-30 10:00:00',
                'title_ms' => 'Di sebalik tabir: carian dwibahasa',
                'title_en' => 'Behind the scenes: bilingual search',
                'excerpt_ms' => 'Bagaimana satu kotak carian memberi keputusan yang tepat dalam dua bahasa tanpa perkhidmatan luar.',
                'excerpt_en' => 'How one search box returns accurate results in two languages without an external service.',
                'content_ms' => '<p>Setiap kali kandungan diterbitkan, portal menyalin tajuk dan teks ke dalam satu jadual indeks dengan lajur berasingan untuk Bahasa Malaysia dan Bahasa Inggeris. PostgreSQL membina indeks teks penuh bagi setiap lajur, jadi carian berjalan di dalam pangkalan data yang sama tanpa perkhidmatan tambahan.</p><p>Keputusan disusun mengikut keutamaan jenis kandungan dan skor padanan. Pentadbir juga boleh menambah pautan pilihan untuk kata kunci tertentu, contohnya memaparkan halaman Hubungi Kami di bahagian atas apabila pelawat mencari perkataan "hubungi".</p><p>Pendekatan ini mengekalkan kos rendah dan memudahkan pemasangan oleh agensi kecil.</p>',
                'content_en' => '<p>Whenever content is published, the portal copies its title and text into a single index table with separate columns for Bahasa Malaysia and English. PostgreSQL builds a full-text index on each column, so search runs inside the same database without an extra service.</p><p>Results are ranked by content type priority and match score. Administrators can also add promoted links for specific keywords, for example showing the Contact Us page at the top when a visitor searches for "contact".</p><p>This approach keeps costs low and makes installation straightforward for small agencies.</p>',
            ],
            [
                'slug' => 'dasar-privasi-portal-dikemas-kini',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-06-16 09:00:00',
                'title_ms' => 'Dasar Privasi portal dikemas kini',
                'title_en' => 'Portal Privacy Policy updated',
                'excerpt_ms' => 'Kemas kini menjelaskan data yang disimpan oleh borang maklum balas dan pembantu AI.',
                'excerpt_en' => 'The update explains what data the feedback form and the AI assistant store.',
                'content_ms' => '<p>Dasar Privasi portal telah dikemas kini pada 16 Jun 2026. Perubahan utama:</p><ul><li>Bahagian baharu mengenai pembantu AI, termasuk tempoh simpanan perbualan dan cara ia dipadam secara automatik.</li><li>Penjelasan bahawa alamat IP pada borang maklum balas digunakan hanya untuk had kadar dan dipadam selepas 30 hari.</li><li>Senarai kuki yang digunakan, iaitu kuki sesi, kuki tema dan kuki bahasa sahaja.</li></ul><p>Versi penuh boleh dibaca pada halaman Dasar Privasi di kaki laman.</p>',
                'content_en' => '<p>The portal Privacy Policy was updated on 16 June 2026. The main changes:</p><ul><li>A new section on the AI assistant, including how long conversations are kept and how they are deleted automatically.</li><li>Clarification that the IP address on the feedback form is used only for rate limiting and removed after 30 days.</li><li>A list of the cookies in use, which are the session, theme and language cookies only.</li></ul><p>The full version is available on the Privacy Policy page in the footer.</p>',
            ],
            [
                'slug' => 'sistem-tema-baharu-untuk-portal',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-05-19 09:00:00',
                'title_ms' => 'Sistem tema baharu untuk portal',
                'title_en' => 'New theme system for the portal',
                'excerpt_ms' => 'Tema kini boleh ditukar oleh pentadbir tanpa menyentuh kod, dengan tema lalai berasaskan MyDS.',
                'excerpt_en' => 'Themes can now be switched by administrators without touching code, with a default theme based on MyDS.',
                'content_ms' => '<p>Sistem tema memisahkan paparan awam daripada logik aplikasi. Setiap tema mempunyai fail manifes, lembaran gaya dan set paparan sendiri, dan pentadbir boleh memilih tema aktif melalui panel pentadbiran.</p><p>Tema lalai mengikut token reka bentuk MyDS: skala warna biru, fon Poppins untuk tajuk dan Inter untuk teks badan, serta jejari dan bayang yang konsisten. Pembangun boleh menyalin tema lalai sebagai titik permulaan untuk jenama agensi mereka.</p><p>Piawaian pembangunan tema didokumentasikan di halaman Dasar.</p>',
                'content_en' => '<p>The theme system separates the public presentation from application logic. Each theme has its own manifest file, stylesheet and set of views, and administrators can pick the active theme from the admin panel.</p><p>The default theme follows MyDS design tokens: the blue colour scale, Poppins for headings and Inter for body text, plus consistent radii and shadows. Developers can copy the default theme as a starting point for their agency brand.</p><p>The theme development standards are documented on the Policy page.</p>',
            ],
            [
                'slug' => 'perjumpaan-komuniti-sumber-terbuka-pertama',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-05-05 14:00:00',
                'title_ms' => 'Perjumpaan komuniti sumber terbuka pertama',
                'title_en' => 'First open-source community meetup',
                'excerpt_ms' => 'Empat puluh penyumbang berkumpul untuk berkongsi pemasangan, tema dan idea ciri baharu.',
                'excerpt_en' => 'Forty contributors gathered to share installations, themes and ideas for new features.',
                'content_ms' => '<p>Perjumpaan komuniti OpenGovPortal yang pertama diadakan secara hibrid pada 5 Mei 2026 dengan empat puluh peserta dari agensi, universiti dan syarikat pembangunan perisian.</p><p>Sesi perkongsian merangkumi pemasangan portal di persekitaran kontena, tema tersuai untuk perpustakaan awam dan cadangan untuk penerbitan berjadual. Tiga daripada cadangan tersebut telah dimasukkan ke dalam pelan hala tuju.</p><p>Perjumpaan seterusnya dirancang pada suku keempat 2026. Butiran akan disiarkan di halaman ini.</p>',
                'content_en' => '<p>The first OpenGovPortal community meetup was held in hybrid format on 5 May 2026 with forty participants from agencies, universities and software companies.</p><p>Sharing sessions covered installing the portal in a container environment, a custom theme for public libraries and proposals for scheduled publishing. Three of those proposals have since been added to the roadmap.</p><p>The next meetup is planned for the fourth quarter of 2026. Details will be posted on this page.</p>',
            ],
            [
                'slug' => 'had-kadar-baharu-untuk-borang-maklum-balas',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-04-21 09:00:00',
                'title_ms' => 'Had kadar baharu untuk borang maklum balas',
                'title_en' => 'New rate limit for the feedback form',
                'excerpt_ms' => 'Setiap alamat IP kini dihadkan kepada lima penghantaran sejam untuk mengurangkan spam.',
                'excerpt_en' => 'Each IP address is now limited to five submissions per hour to reduce spam.',
                'content_ms' => '<p>Mulai 21 April 2026, borang maklum balas di halaman Hubungi Kami menghadkan setiap alamat IP kepada lima penghantaran sejam. Had ini diperkenalkan selepas peningkatan mesej automatik pada bulan Mac.</p><p>Pengguna biasa tidak akan terkesan. Jika had dicapai, borang memaparkan mesej yang jelas bersama masa cubaan semula. Mesej yang telah dihantar sebelum had dicapai tetap disimpan.</p>',
                'content_en' => '<p>From 21 April 2026, the feedback form on the Contact Us page limits each IP address to five submissions per hour. The limit was introduced after a rise in automated messages in March.</p><p>Regular users will not be affected. If the limit is reached, the form shows a clear message with the time to try again. Messages sent before the limit was reached are still stored.</p>',
            ],
            [
                'slug' => 'dokumentasi-portal-dikemas-kini-sepenuhnya',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-04-07 10:00:00',
                'title_ms' => 'Dokumentasi portal dikemas kini sepenuhnya',
                'title_en' => 'Portal documentation fully refreshed',
                'excerpt_ms' => 'Tiga belas dokumen merangkumi seni bina, skema, keselamatan dan pengujian kini selari dengan kod.',
                'excerpt_en' => 'Thirteen documents covering architecture, schema, security and testing are now in step with the code.',
                'content_ms' => '<p>Dokumentasi projek telah disemak sepenuhnya supaya setiap dokumen sepadan dengan kod yang dijalankan. Set ini merangkumi panduan pemasangan, seni bina, skema pangkalan data, strategi cache, keselamatan, pengujian dan rujukan API.</p><p>Setiap halaman kini mempunyai bahagian rujukan silang dan contoh arahan yang boleh dijalankan. Penyumbang digalakkan membaca panduan pengekodan sebelum menghantar perubahan.</p>',
                'content_en' => '<p>The project documentation has been reviewed in full so that every document matches the running code. The set covers installation, architecture, database schema, caching strategy, security, testing and the API reference.</p><p>Every page now has a cross-reference section and runnable example commands. Contributors are encouraged to read the coding guide before submitting changes.</p>',
            ],
            [
                'slug' => 'opengovportal-0-6-0-semua-halaman-awam-siap',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-03-24 09:00:00',
                'title_ms' => 'OpenGovPortal 0.6.0: semua halaman awam siap',
                'title_en' => 'OpenGovPortal 0.6.0: all public pages complete',
                'excerpt_ms' => 'Kesemua sepuluh halaman awam, menu kebolehcapaian dan sistem tema kini tersedia dalam satu keluaran.',
                'excerpt_en' => 'All ten public pages, the accessibility menu and the theme system arrive in a single release.',
                'content_ms' => '<p>Versi 0.6.0 menandakan tamatnya fasa pembinaan halaman awam. Laman utama, siaran, pencapaian, statistik, direktori, dasar, profil organisasi, hubungi kami, penafian dan dasar privasi kini tersedia dalam Bahasa Malaysia dan Bahasa Inggeris.</p><p>Keluaran ini juga memperkenalkan menu kebolehcapaian dengan pilihan saiz fon, jenis fon dan warna latar, sistem tema, sokongan Google Analytics dan aliran lupa kata laluan untuk pentadbir.</p><p>Fasa seterusnya memberi tumpuan kepada prestasi, cache halaman penuh dan penerbitan berjadual.</p>',
                'content_en' => '<p>Version 0.6.0 marks the end of the public page build-out. The homepage, broadcasts, achievements, statistics, directory, policies, organisation profile, contact us, disclaimer and privacy policy pages are now available in Bahasa Malaysia and English.</p><p>This release also introduces the accessibility menu with font size, font type and background colour options, the theme system, Google Analytics support and a forgotten-password flow for administrators.</p><p>The next phase focuses on performance, full-page caching and scheduled publishing.</p>',
            ],
            [
                'slug' => 'statistik-portal-kini-dengan-carta-interaktif',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-03-10 10:00:00',
                'title_ms' => 'Statistik portal kini dengan carta interaktif',
                'title_en' => 'Portal statistics now with interactive charts',
                'excerpt_ms' => 'Halaman Statistik memaparkan carta garisan, bar dan donat yang boleh dikemas kini oleh pentadbir.',
                'excerpt_en' => 'The Statistics page shows line, bar and doughnut charts that administrators can update.',
                'content_ms' => '<p>Halaman Statistik kini memaparkan carta interaktif dengan petunjuk dan legenda yang boleh diklik. Pentadbir menentukan tajuk, jenis carta dan data melalui halaman Urus Statistik tanpa perubahan kod.</p><p>Carta dipaparkan menggunakan pustaka sumber terbuka dan mengikut warna tema aktif. Setiap carta mempunyai tajuk dan keterangan dalam dua bahasa.</p>',
                'content_en' => '<p>The Statistics page now shows interactive charts with tooltips and clickable legends. Administrators define the title, chart type and data on the Manage Statistics page without any code changes.</p><p>Charts are rendered with an open-source library and follow the colours of the active theme. Every chart has a title and description in both languages.</p>',
            ],
            [
                'slug' => 'direktori-kakitangan-kini-boleh-dicari-secara-langsung',
                'type' => 'announcement',
                'status' => 'published',
                'published_at' => '2026-02-24 09:00:00',
                'title_ms' => 'Direktori kakitangan kini boleh dicari secara langsung',
                'title_en' => 'Staff directory now searchable in real time',
                'excerpt_ms' => 'Taip nama, jawatan atau jabatan dan senarai dikemas kini serta-merta tanpa memuat semula halaman.',
                'excerpt_en' => 'Type a name, position or department and the list updates instantly without reloading the page.',
                'content_ms' => '<p>Halaman Direktori kini menyokong carian langsung. Keputusan ditapis semasa anda menaip, dan penapis jabatan memaparkan hanya jabatan yang mempunyai kakitangan aktif dalam bahasa antara muka semasa.</p><p>Setiap kad kakitangan memaparkan nama, jawatan, jabatan, emel dan telefon. Pautan emel dan telefon boleh diklik pada peranti mudah alih.</p>',
                'content_en' => '<p>The Directory page now supports live search. Results are filtered as you type, and the department filter lists only departments with active staff in the current interface language.</p><p>Each staff card shows the name, position, department, email and phone. Email and phone links are tappable on mobile devices.</p>',
            ],
            [
                'slug' => 'lima-petua-menulis-kandungan-dwibahasa',
                'type' => 'news',
                'status' => 'published',
                'published_at' => '2026-02-10 10:00:00',
                'title_ms' => 'Lima petua menulis kandungan dwibahasa',
                'title_en' => 'Five tips for writing bilingual content',
                'excerpt_ms' => 'Tulis dalam bahasa pertama dahulu, kekalkan ayat pendek dan semak istilah dengan glosari.',
                'excerpt_en' => 'Write in the first language first, keep sentences short and check terms against the glossary.',
                'content_ms' => '<p>Kandungan dwibahasa yang baik bukan terjemahan perkataan demi perkataan. Lima petua daripada pasukan editorial:</p><ol><li>Tulis versi Bahasa Malaysia sepenuhnya dahulu, kemudian tulis semula dalam Bahasa Inggeris dengan makna yang sama.</li><li>Kekalkan ayat kurang daripada 25 patah perkataan. Ayat pendek lebih mudah diterjemah dan dibaca.</li><li>Gunakan glosari istilah portal supaya nama ciri konsisten dalam kedua-dua bahasa.</li><li>Elakkan singkatan tanpa penerangan pada penggunaan pertama.</li><li>Baca kedua-dua versi dengan suara lantang sebelum menerbitkan.</li></ol>',
                'content_en' => '<p>Good bilingual content is not a word-for-word translation. Five tips from the editorial team:</p><ol><li>Write the full Bahasa Malaysia version first, then rewrite it in English with the same meaning.</li><li>Keep sentences under 25 words. Short sentences are easier to translate and to read.</li><li>Use the portal glossary so feature names stay consistent in both languages.</li><li>Avoid abbreviations without an explanation on first use.</li><li>Read both versions aloud before publishing.</li></ol>',
            ],
            [
                'slug' => 'kod-sumber-opengovportal-kini-terbuka',
                'type' => 'press_release',
                'status' => 'published',
                'published_at' => '2026-01-14 09:00:00',
                'title_ms' => 'Kod sumber OpenGovPortal kini terbuka',
                'title_en' => 'OpenGovPortal source code is now open',
                'excerpt_ms' => 'Repositori awam dibuka bersama dokumentasi, pelan hala tuju dan panduan penyumbang.',
                'excerpt_en' => 'The public repository opens with documentation, a roadmap and a contributor guide.',
                'content_ms' => '<p>Kod sumber OpenGovPortal kini tersedia secara terbuka. Repositori merangkumi aplikasi penuh, dokumentasi, pelan hala tuju dan panduan untuk penyumbang.</p><p>Matlamat kami ialah membolehkan mana-mana agensi awam memasang portal dwibahasa yang mudah diakses dalam masa satu hari, dan menyesuaikannya tanpa bergantung kepada vendor tunggal.</p><p>Sumbangan berbentuk laporan pepijat, terjemahan, tema dan dokumentasi dialu-alukan. Sila baca panduan penyumbang sebelum menghantar permintaan tarik.</p>',
                'content_en' => '<p>The OpenGovPortal source code is now openly available. The repository includes the full application, documentation, the roadmap and a guide for contributors.</p><p>Our goal is to let any public agency install a bilingual, accessible portal within a day and adapt it without depending on a single vendor.</p><p>Contributions in the form of bug reports, translations, themes and documentation are welcome. Please read the contributor guide before opening a pull request.</p>',
            ],
            [
                'slug' => 'pelan-hala-tuju-opengovportal-2027',
                'type' => 'press_release',
                'status' => 'draft',
                'published_at' => null,
                'title_ms' => 'Pelan hala tuju OpenGovPortal 2027',
                'title_en' => 'OpenGovPortal 2027 roadmap',
                'excerpt_ms' => 'Draf pelan hala tuju untuk tahun 2027, termasuk penerbitan berjadual dan sokongan berbilang agensi.',
                'excerpt_en' => 'Draft roadmap for 2027, including scheduled publishing and multi-agency support.',
                'content_ms' => '<p>Draf ini masih dalam semakan. Fokus utama untuk 2027 ialah penerbitan berjadual, sokongan berbilang agensi dalam satu pemasangan dan alat import kandungan daripada sistem sedia ada.</p>',
                'content_en' => '<p>This draft is still under review. The main focus areas for 2027 are scheduled publishing, multi-agency support in a single installation and content import tools from existing systems.</p>',
            ],
        ];
    }
}
